# Generated by Django 5.1.3 on 2025-01-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_title', models.CharField(max_length=255)),
                ('established_in', models.IntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('wh_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('event_photos', models.ImageField(null=True, upload_to='image/')),
                ('rating', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to='userapp.usersignup')),
                ('select_services', models.ManyToManyField(related_name='events', to='eventapp.service')),
            ],
            options={
                'db_table': 'create_events',
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eventapp.createevent')),
            ],
            options={
                'db_table': 'event_images',
            },
        ),
    ]
